[workspace]
authors = ["akiyuki ishikawa <aki.y.ishikawa@gmail.com>"]
channels = ["conda-forge"]
name = "ipython-pathlib-completer"
platforms = ["osx-arm64"]
version = "0.1.0"

[dependencies]
ipython = ">=9.8.0,<10"

[environments]
dev = ["dev"]

[feature.dev.dependencies]
jupyterlab = ">=4.5.1,<5"
pytest = ">=8.3.2,<9"
parso = ">=0.8.4,<0.9"

[feature.dev.tasks]
jupyterlab = "jupyter lab"
test = "pytest tests/"

[pypi-dependencies]
ipython-pathlib-completer = { path = "./", editable = true }
